name: Deployment Digital Garden ETH

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages # branch to synchronise from
      - name: Deploy to server
        run: rsync -avz . ${SSH_USERNAME}@${SSH_HOST}:/homepage/digital-garden
